import yfinance as yf

#fujikura = yf.Ticker("5803.T")
#data = fujikura.history(period="10y")
#data.to_csv("fujikura_10y.csv")

#advantest = yf.Ticker("6857.T")
#data = advantest.history(period="10y")
#data.to_csv("advantest_10y.csv")

#ibiden = yf.Ticker("4062.T")
#data = ibiden.history(period="10y")
#data.to_csv("ibiden_10y.csv")

#lasertec = yf.Ticker("6920.T")
#data = lasertec.history(period="10y")
#data.to_csv("lasertec_10y.csv")

#appier = yf.Ticker("4180.T")
#data = appier.history(period="10y")
#data.to_csv("appier_10y.csv")

#sumco = yf.Ticker("3436.T")
#data = sumco.history(period="10y")
#data.to_csv("sumco_10y.csv")

#screen = yf.Ticker("7735.T")
#data = screen.history(period="10y")
#data.to_csv("screen_10y.csv")

#hoya = yf.Ticker("7741.T")
#data = hoya.history(period="10y")
#data.to_csv("hoya_10y.csv")

#rohm = yf.Ticker("6963.T")
#data = rohm.history(period="10y")
#data.to_csv("rohm_10y.csv")

#kokusai = yf.Ticker("6525.T")
#data = kokusai.history(period="10y")
#data.to_csv("kokusai_10y.csv")

#shinetsu = yf.Ticker("4063.T")
#data = shinetsu.history(period="10y")
#data.to_csv("shinetsu_10y.csv")

#tel = yf.Ticker("8035.T")
#data = tel.history(period="10y")
#data.to_csv("tel_10y.csv")

def fetch_data(code, name):
    ticker = yf.Ticker(code + ".T")
    data = ticker.history(period="10y")
    data.to_csv(name + "_10y.csv")

if __name__ == '__main__':
    #fetch_data("5801", "furukawa")
    #fetch_data("6902", "denso")
    #fetch_data("4519", "chugai")
    #fetch_data("4503", "astellas")
    #fetch_data("4507", "shionogi")
    #fetch_data("7974", "nintendo")
    #fetch_data("9697", "capcom")
    #fetch_data("7832", "bandai")
    #fetch_data("9503", "kepco")
    #fetch_data("9501", "tepco")
    #fetch_data("5020", "enos")
    #fetch_data("7011", "mhi")
    #fetch_data("7013", "ihi")
    #fetch_data("7012", "khi")
    #fetch_data("8001", "itochu")
    #fetch_data("8058", "mitsubishi")
    #fetch_data("8031", "mitsui")
    #fetch_data("9201", "jal")
    #fetch_data("9202", "ana")
    #fetch_data("4661", "olc")
    #fetch_data("9020", "jreast")
    #fetch_data("7203", "toyota")
    #fetch_data("7201", "nissan")
    #fetch_data("5401", "nipponsteel")
    #fetch_data("5411", "jfeh")
    #fetch_data("9101", "nyk")
    #fetch_data("9104", "mol")
    #fetch_data("9107", "kilne")
    #fetch_data("2801", "kikkoman")
    #fetch_data("2802", "ajinomoto")
    #fetch_data("2282", "nipponham")
    #fetch_data("8136", "sanrio")
    #fetch_data("9766", "konami")
    #fetch_data("9684", "squareenix")
    #fetch_data("7269", "suzuki")
    #fetch_data("7270", "subaru")
    fetch_data("6146", "disco")
    fetch_data("6723", "renesas")
    fetch_data("9984", "softbankg")
    fetch_data("9432", "ntt")
    fetch_data("9433", "kddi")
    fetch_data("9434", "softbank")
    fetch_data("4751", "cyberagent")
    fetch_data("4755", "rakuten")
    fetch_data("4689", "zh")
    fetch_data("6702", "fujitsu")
    fetch_data("6701", "nec")
    fetch_data("6645", "omron")

#print(data)
#print(type(data))
#with open("fujikura.csv", "w", encoding="utf-8") as f:
#    f.write(str(data))